### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by rish-2507** [itschasa/Discord-Backup#17]
Traceback (most recent call last):
  File "main.py", line 182, in <module>
  File "restore.py", line 17, in __init__
AttributeError: 'restore' object has no attribute 'c'
[9764] Failed to execute script 'main' due to unhandled exception!

**Comment by itschasa** [comment]
Dup of #12, its being looked into.

**Comment by itschasa** [comment]
Duplicate of #12, its being looked into.
