### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by millxisyes** [itschasa/Discord-Backup#25]

**Comment by itschasa** [comment]
![try-it-and-see-give-it-a-try](https://github.com/itschasa/Discord-Backup/assets/79016507/9929cc45-ab5f-477d-8b8b-92a9eaf65e73)

no idea, give it a go (use source code, mac's dont like exe's surprisingly)

**Comment by infamous-koala** [comment]
i dont think mac os will be supported, I did test and fix it for linux so it **_should_** work for mac but idk maybe yes or no

**Comment by BackslashG** [comment]
I edge to pictures of this

**Comment by itschasa** [comment]
> I edge to pictures of this

😳

**Comment by itschasa** [comment]
If anyone can test if this script on MacOS, then please do. I'm happy to fix bugs to make it work on macs as well.

**Comment by millxisyes** [comment]
Idk how to run source code

**Comment by infamous-koala** [comment]
> Idk how to run source code

what do u mean by that 💀

**Comment by millxisyes** [comment]
how do i run a windows program on mac bro i thought i was supposed to runt
he source code or ws0ometbhuifoel;sdajm,.saol

**Comment by BackslashG** [comment]
you run the source code silly billy
https://github.com/itschasa/Discord-Backup?tab=readme-ov-file#using-source

**Comment by millxisyes** [comment]
oh

**Comment by millxisyes** [comment]
I find myself reading fan fics about this repository

**Comment by itschasa** [comment]
> I find myself reading fan fics about this repository

😳

**Comment by infamouskoala** [comment]
mm chasa im gonna be in the fanfic i swear 😏

**Comment by BackslashG** [comment]
I LOVE YOU MILLX
LETS HAVE HOT GAY ANAL SEX AT UR HOUSE TMRW!! <3

**Comment by infamouskoala** [comment]
> I LOVE YOU MILLX LETS HAVE HOT GAY ANAL SEX AT UR HOUSE TMRW!! <3

CAN I JOIN PLEASE??????????????

**Comment by BackslashG** [comment]
Chop chop millx any day now

**Comment by millxisyes** [comment]
can confirm that it does NOT have mac support

**Comment by itschasa** [comment]
> can confirm that it does NOT have mac support

What makes it not have mac support? Any errors?

**Comment by millxisyes** [comment]
@itschasa this is the error i got:
Traceback (most recent call last):
  File "/Users/verbog/Downloads/Discord-Backup-1.2.10/main.py", line 136, in <module>
    import fetch_tokens
  File "/Users/verbog/Downloads/Discord-Backup-1.2.10/fetch_tokens.py", line 13, in <module>
    from win32crypt import CryptUnprotectData
ModuleNotFoundError: No module named 'win32crypt'

**Comment by BackslashG** [comment]
Did you pip install the module?    ---- On Tue, 30 Jul 2024 21:26:30 -0500  ***@***.******@***.***> wrote ----  
@itschasa this is the error i got: 
Traceback (most recent call last): 
File "/Users/verbog/Downloads/Discord-Backup-1.2.10/main.py", line 136, in  
import fetch_tokens 
File "/Users/verbog/Downloads/Discord-Backup-1.2.10/fetch_tokens.py", line 13, in  
from win32crypt import CryptUnprotectData 
ModuleNotFoundError: No module named 'win32crypt'

**Comment by itschasa** [comment]
Ah of course win32crypt won't work on MacOS. Maybe in the future, I'll make it so tokens can be fetched automatically on MacOS.

**Comment by millxisyes** [comment]
@itschasa looking forward to when that happens

**Comment by itschasa** [comment]
> @itschasa looking forward to when that happens

give it a few years 😅

**Comment by BackslashG** [comment]
don't fix it make millx mad

**Comment by millxisyes** [comment]
i already have a windows machine to back up on so idrc if it gets a macOS
release or not now

**Comment by BackslashG** [comment]
can i have ur macbook
